name: siparis_sistemi1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  mobile_scanner: ^7.0.1
  pdf: ^3.8.1
  printing: ^5.12.0
  path_provider: ^2.0.15
  intl: ^0.18.0
  open_file: ^3.2.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.7
  dio: ^5.2.1
  flutter_pdfview: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/logo.png
